DROP TABLE IF EXISTS wishlist_books;
DROP TABLE IF EXISTS wishlist;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS library_member;


ALTER TABLE IF EXISTS book
    ADD COLUMN good_condition BOOLEAN NOT NULL DEFAULT true

UPDATE book
SET good_condition = true
WHERE good_condition IS NULL;

CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    continent VARCHAR(500) NOT NULL
);

CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    country_id BIGINT REFERENCES country
);

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    author_id BIGINT REFERENCES author,
    available_copies BIGINT NOT NULL,
    good_condition BOOLEAN NOT NULL DEFAULT TRUE,
--     is_rented BOOLEAN DEFAULT FALSE
);

CREATE TABLE library_member (
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    is_account_non_expired BOOLEAN DEFAULT TRUE,
    is_account_non_locked BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled BOOLEAN DEFAULT TRUE,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_created TIMESTAMP NOT NULL,
    user_username VARCHAR(255) REFERENCES library_member,
    UNIQUE (user_username)
);

CREATE TABLE wishlist_books (
    wishlist_id BIGINT REFERENCES wishlist ON DELETE CASCADE,
    book_id BIGINT REFERENCES book ON DELETE CASCADE,
    PRIMARY KEY (wishlist_id, book_id)
);

CREATE INDEX idx_user_username_password ON library_member (username, password);
CREATE INDEX idx_user_username ON library_member (username);
CREATE INDEX idx_user_role ON library_member (role); 